---
title: "MLB Run Expectancies"
author: "Ben Ellman"
date: "2024-08-20"
output: html_document
---

#load packages
library(tidyverse)
library(ggplot2)
library(data.table)
library(retrosheet)

#USE STATCAST DATA -- has count info, pitch result (to get diff btw ball vs strike), pre-pitch score and post-pitch score -- see if you can get just stats w/ at-bat result to limit overall data pull

#run expectancy matrix (expected runs for base-out state 2024)
#get at-bat data for all at-bats in 2024, group_by 8 baserunner situations and three out situations, total runs scored/situation to arrive at expected runs for each of the 24 possible states
#8x3 matrix of base states to outs with values equal to average time a run was scored from that state

#download play-by-play data for 2023 year from retrosheet.org using retrosheet package (large data requires breaking up into separate lists and then appending together for the final data frame)
team_ids <- c('ANA', 'ARI', 'ATL', 'BAL', 'BOS', 'CHA', 'CHN', 'CIN', 'CLE', 'COL', 'DET', 'HOU', 'KCA', 'LAN', 'MIA', 'MIL', 'MIN', 'NYA', 'NYN', 'OAK', 'PHI', 'PIT', 'SDN', 'SEA', 'SFN', 'SLN', 'TBA', 'TEX', 'TOR', 'WAS')

plays_1 <- tibble()
result_list1 <- list()

for (j in seq_along(team_ids)) {
  for(i in 1:13) {
    plays_1 <- get_retrosheet("play",2023,team_ids[j])[[i]]$play
    result_list1[[paste(j, i, 2023, sep = "_")]] <- plays_1
}
}

plays_2 <- tibble()
result_list2 <- list()

for (j in seq_along(team_ids)) {
  for(i in 14:27) {
    plays_2 <- get_retrosheet("play",2023,team_ids[j])[[i]]$play
    result_list2[[paste(j, i, 2023, sep = "_")]] <- plays_2
}
}

plays_3 <- tibble()
result_list3 <- list()

for (j in seq_along(team_ids)) {
  for(i in 28:41) {
    plays_3 <- get_retrosheet("play",2023,team_ids[j])[[i]]$play
    result_list3[[paste(j, i, 2023, sep = "_")]] <- plays_3
}
}

plays_4 <- tibble()
result_list4 <- list()

for (j in seq_along(team_ids)) {
  for(i in 42:55) {
    plays_4 <- get_retrosheet("play",2023,team_ids[j])[[i]]$play
    result_list4[[paste(j, i, 2023, sep = "_")]] <- plays_4
}
}

plays_5 <- tibble()
result_list5 <- list()

for (j in seq_along(team_ids)) {
  for(i in 56:68) {
    plays_5 <- get_retrosheet("play",2023,team_ids[j])[[i]]$play
    result_list5[[paste(j, i, 2023, sep = "_")]] <- plays_5
}
}

plays_6 <- tibble()
result_list6 <- list()

for (j in seq_along(team_ids)) {
  for(i in 69:81) {
    plays_6 <- get_retrosheet("play",2023,team_ids[j])[[i]]$play
    result_list6[[paste(j, i, 2023, sep = "_")]] <- plays_6
}
}

combined_list <- c(result_list1, result_list2, result_list3, result_list4, result_list5, result_list6)

plays_23 <- do.call(rbind, combined_list)

#remove unnecessary dataframes that were appended to get plays_23
rm(list = c("plays_1", "plays_2", "plays_3", "plays_4", "plays_5", "plays_6", "result_list1", "result_list2", "result_list3", "result_list4", "result_list5", "result_list6", "combined_list"))

#use plays_23 (play by play data for 2023) to approximate run expectancy given each base runner-out state

#re-worked base-state conditional statements
#start by defining first, second, third, etc. as basic events (Hit, walk, advance)
#use lag(play) to assign base values to bases_empty values that 
#get exceptions (SB, DP, CS)



#add in base state (bases occupied during at bat) to plays_23 using retorsheet coding rules
plays_23 <- plays_23 %>%
mutate(base_state = case_when(
(grepl("\\.1|;1",play) & grepl("\\.3|;3",play) & grepl("\\.2|;2",play)) | (grepl("^S.|^W.|.B-1",lag(play)) & grepl(".1-2",lag(play)) & grepl(".2-3",lag(play))) ~ "bases_loaded",
((grepl("\\.1|;1",play) & grepl("\\.2|;2",play)) | (grepl("^S.|^W.|.B-1",lag(play)) & grepl("1-2",lag(play)))) & !(grepl("\\.3|;3",play) | grepl("^HR|^SB",lag(play))) ~ "first_second",
((grepl("\\.1|;1",play) & grepl("\\.3|;3",play)) | (grepl("^S.|^W.|.B-1",lag(play)) & grepl(".1-3|.2-3",lag(play)))) & !(grepl("\\.2|;2",play) | grepl("^HR|^SB",lag(play))) ~ "first_third",
((grepl("\\.2|;2",play) & grepl("\\.3|;3",play)) | (grepl("^D.|.B-2|^DGR",lag(play))) & grepl(".1-3|.2-3",lag(play))) & !(grepl("\\.1|;1",play) | grepl("^HR",lag(play))) ~ "second_third",
(grepl("\\.1|;1",play) | grepl("^S|^W|B-1",lag(play))) & !(grepl("\\.2|;2|\\.3|;3",play) | grepl("1-2|1-3|2-3|B-2|B-3|^HR",lag(play))) ~ "first",
(grepl("\\.2|;2",play) | grepl("^D|B-2|1-2|^DGR",lag(play))) & !(grepl("\\.1|;1|\\.3|;3",play) | grepl("2-3|B-3|^HR",lag(play))) ~ "second",
(grepl("\\.3|;3",play) | grepl("^T|B-3|1-3|2-3",lag(play))) & !(grepl("\\.2|;2|\\.1|;1",play) | grepl("B-H|^HR",lag(play))) ~ "third",
TRUE ~ "bases_empty"
))

plays_23 <- plays_23 %>%
mutate(base_state = case_when(
base_state == "bases_empty" & team == lag(team) & !grepl("^HR|^CS|^POCS",lag(play)) ~ lag(base_state),
TRUE ~ base_state
))

plays_23 <- plays_23 %>%
mutate(base_state = case_when(
base_state == lag(base_state) & base_state == "first_second" & lag(team) == team & grepl("2-H",lag(play)) & !grepl("\\.1|;1",lag(play)) ~ "first",
base_state == lag(base_state) & base_state == "first_second" & lag(team) == team & grepl("2-H",lag(play)) & grepl("1-H",lag(play)) ~ "bases_empty",
base_state == lag(base_state) & base_state == "first_third" & lag(team) == team & grepl("3-H",lag(play)) & !grepl("\\.1|;1",lag(play)) ~ "first",
base_state == lag(base_state) & base_state == "first_third" & lag(team) == team & grepl("3-H",lag(play)) & grepl("1-H",lag(play)) ~ "bases_empty", 
base_state == lag(base_state) & base_state == "second_third" & lag(team) == team & grepl("3-H",lag(play)) & !grepl("\\.2|;2",lag(play)) ~ "second",
base_state == lag(base_state) & base_state == "second_third" & lag(team) == team & grepl("3-H",lag(play)) & grepl("2-H",lag(play)) ~ "bases_empty",
base_state == lag(base_state) & base_state == "bases_loaded" & lag(team) == team & grepl("3-H",lag(play)) & !(grepl("\\.1|;1",lag(play)) & grepl("\\.2|;2",lag(play)))  ~ "first_second",
base_state == lag(base_state) & base_state == "bases_loaded" & lag(team) == team & grepl("3-H",lag(play)) & grepl("2-H",lag(play)) ~ "first",
base_state == lag(base_state) & base_state == "third" & lag(team) == team & grepl("3-H",lag(play)) ~ "bases_empty",
TRUE ~ base_state
))

plays_23 <- plays_23 %>%
mutate(base_state = case_when(
base_state == "bases_empty" & team == lag(team) & !grepl("^HR|^CS|^POCS",lag(play)) ~ lag(base_state),
TRUE ~ base_state
))

plays_23 <- plays_23 %>%
mutate(base_state = case_when(
base_state == lag(base_state) & base_state == "first_second" & lag(team) == team & grepl("2-H",lag(play)) & !grepl("\\.1|;1",lag(play)) ~ "first",
base_state == lag(base_state) & base_state == "first_second" & lag(team) == team & grepl("2-H",lag(play)) & grepl("1-H",lag(play)) ~ "bases_empty",
base_state == lag(base_state) & base_state == "first_third" & lag(team) == team & grepl("3-H",lag(play)) & !grepl("\\.1|;1",lag(play)) ~ "first",
base_state == lag(base_state) & base_state == "first_third" & lag(team) == team & grepl("3-H",lag(play)) & grepl("1-H",lag(play)) ~ "bases_empty", 
base_state == lag(base_state) & base_state == "second_third" & lag(team) == team & grepl("3-H",lag(play)) & !grepl("\\.2|;2",lag(play)) ~ "second",
base_state == lag(base_state) & base_state == "second_third" & lag(team) == team & grepl("3-H",lag(play)) & grepl("2-H",lag(play)) ~ "bases_empty",
base_state == lag(base_state) & base_state == "bases_loaded" & lag(team) == team & grepl("3-H",lag(play)) & !(grepl("\\.1|;1",lag(play)) & grepl("\\.2|;2",lag(play)))  ~ "first_second",
base_state == lag(base_state) & base_state == "bases_loaded" & lag(team) == team & grepl("3-H",lag(play)) & grepl("2-H",lag(play)) ~ "first",
base_state == lag(base_state) & base_state == "third" & lag(team) == team & grepl("3-H",lag(play)) ~ "bases_empty",
TRUE ~ base_state
))

#TEST before running (and check SB grepl filters in first base_state code block)
plays_23 <- plays_23 %>%
mutate(base_state = case_when(
base_state == "first" & team == lag(team) & grepl("SB2",lag(play)) & !grepl("SB3|2-3|1-3",lag(play)) ~ "second",

base_state == "second" & team == lag(team) & grepl("SB3|2-3|1-3", lag(play)) & !grepl("SB2|1-2",lag(play)) ~ "third"

#check before running below code to finish base_state
plays_23 %>% mutate(test_lead = lead(base_state)) %>% subset(test_lead != post_ab_base_state) %>% View()

plays_23 <- plays_23 %>%
mutate(post_ab_base_state = lead(base_state))

#going to need to get game/inning column to get # of outs
#number of outs column


#run_scored binary column

#run expectancy for each base-out state

#value of strike vs. ball in given count

